USE QLKTX
GO
-- FUNCTION


--hash md5 tạo chuỗi băm md5 t-sql
CREATE OR ALTER FUNCTION UFN_GenerateMD5 (@PlanTText VARCHAR(32))
	RETURNS VARCHAR(32)
AS
BEGIN
	RETURN CONVERT(VARCHAR(32), HashBytes('MD5', @PlantText), 2)
END
GO
--1. hàm lấy mã tỉnh bằng tên tỉnh
CREATE OR ALTER FUNCTION UFN_LayMaTinhBangTenTinh(@TENTINHTHANH NVARCHAR(20))
	RETURNS VARCHAR(2)
AS
BEGIN
	DECLARE @MATINH VARCHAR(2)
	SELECT @MATINH = MATINH FROM dbo.TINHTHANH
	WHERE TENTINHTHANH = @TENTINHTHANH
	RETURN @MATINH
END
GO

--SELECT dbo.UFN_LayMaTinhBangTenTinh(N'Hà Nội') as MATINHTHANH
-- hàm tạo mật khẩu mặc định
CREATE OR ALTER FUNCTION UFN_NEWPASSWORD (@lastPassword VARCHAR(32), 
											@preFix VARCHAR(4), 
											@size INT)
RETURNS VARCHAR(10)
AS
BEGIN
	IF (@lastPassword = '')
			SET @lastPassword = @preFix + REPLICATE(0, @size - LEN(@preFix))
		DECLARE @newPassword VARCHAR(32)
		SET @lastPassword = LTRIM(RTRIM(@lastPassword))
		SET @size = @size - LEN(@preFix)
		SET @newPassword = @preFix + REPLICATE(0, @size - LEN(@preFix))
		RETURN @newPassword
END
GO
--2. hàm lấy mã huyện bằng tên huyện, mã tỉnh
CREATE OR ALTER FUNCTION UFN_LayMaHuyen (
	@TENHUYEN NVARCHAR(40), 
	@MATINH VARCHAR(2)
)
	RETURNS VARCHAR(3)
AS
BEGIN
	DECLARE @MAHUYEN varchar(3)
	SELECT @MAHUYEN = MAHUYEN FROM dbo.HUYEN
	WHERE TENHUYEN = @TENHUYEN AND MATINH = @MATINH
	RETURN @MAHUYEN
END
GO
--SELECT dbo.UFN_LayMaHuyen(N'Ba Đình', '01') AS MAHUYEN


--3. LẤY MÃ XÃ TỪ TÊN XÃ MÃ HUYỆN
CREATE OR ALTER FUNCTION UFN_LayMaXa(
	@TENXA NVARCHAR(40),
	@MAHUYEN VARCHAR(3)
)
RETURNS VARCHAR(5)
AS
BEGIN
	DECLARE @MAXA VARCHAR(5)
	SELECT @MAXA = MAXA FROM dbo.XA WHERE TENXA = @TENXA AND MAHUYEN = @MAHUYEN
	RETURN @MAXA
END
GO
--SELECT dbo.UFN_LayMaXa(N'Phúc Xá', '001')

--4. HÀM TRẢ VỀ SỐ LƯỢNG SINH VIÊN ĐĂNG KÍ Ở PHÒNG NÀO ĐÓ
CREATE OR ALTER FUNCTION UFN_SoLuongSinhVien
(
	@MAKHUVUC VARCHAR(10),
	@MAPHONG NVARCHAR(10)
)
RETURNS INT
AS BEGIN
	DECLARE @Number INT
	SELECT @Number = COUNT(dbo.DKPHONG.CMND)
	FROM dbo.DKPHONG
	WHERE DKPHONG.MAKHUVUC = @MAKHUVUC
		AND DKPHONG.MAPHONG = @MAPHONG
		AND dbo.DKPHONG.TRANGTHAI = 1
	RETURN @Number
END
GO
--5.lấy danh sách sinh viên theo trạng thái
CREATE OR ALTER FUNCTION DSSV(@TRANGTHAI INT)
RETURNS TABLE
AS
RETURN
SELECT NGUOIDUNG.ID_NGUOIDUNG , CONCAT(NGUOIDUNG.HO , ' ', NGUOIDUNG.TEN) AS HOTEN,NGUOIDUNG.GIOITINH,
       NGUOIDUNG.NGAYSINH,NGUOIDUNG.SĐT1,SINHVIEN.ID_NGUOIDUNG AS MASV, TRUONG.MATRUONG
FROM NGUOIDUNG INNER JOIN DIACHI ON NGUOIDUNG.MADIACHI = DIACHI.MADIACHI
			   INNER JOIN SINHVIEN ON NGUOIDUNG.ID_NGUOIDUNG =  SINHVIEN.ID_NGUOIDUNG
			   INNER JOIN TRUONG ON TRUONG.ID_TRUONG = SINHVIEN.ID_TRUONG
WHERE NGUOIDUNG.TRANGTHAI = @TRANGTHAI OR @TRANGTHAI = 2
GO
SELECT * FROM DBO.DSSV(1)
GO
 --6.Lấy mã hóa đơn theo tên khu vực , mã phòng, tháng và năm
CREATE  FUNCTION UFN_LayMaHoaDon
(
	@TENKHUVUC VARCHAR(10),
	@MAPHONG NVARCHAR(10), 
	@THANG INT, 
	@NAM INT
)
RETURNS INT
AS
BEGIN
	DECLARE @MAKHUVUC VARCHAR(10), 
			@MAHOADON INT

	SELECT @MAKHUVUC = KHUVUC.MAKHUVUC FROM KHUVUC WHERE KHUVUC.TENKHUVUC= @TENKHUVUC
	SELECT @MAHOADON = HOADON.MAHOADON FROM HOADON WHERE HOADON.MAKHUVUC = @MAKHUVUC
														AND HOADON.MAPHONG = @MAPHONG
														AND HOADON.THANG = @THANG
														AND HOADON.NAM = @NAM
    RETURN @MAHOADON
END
GO


 --7. lấy mã xã bằng tên xã và mã huyện
CREATE  FUNCTION UFN_LayMaXaBangTenXaVaMaHuyen (@TENXA NVARCHAR(40), @MAHUYEN VARCHAR(3))
	RETURNS VARCHAR(5)
AS
BEGIN
	DECLARE @MAXA VARCHAR(5)
	SELECT @MAXA = MAXA FROM dbo.XA
	WHERE TENXA = @TENXA AND MAHUYEN =@MAHUYEN
	RETURN @MAXA
END
GO

SELECT dbo.UFN_LayMaXaBangTenXaVaMaHuyen(N'Trúc Bạch','001')
SELECT * FROM XA
SELECT * FROM HUYEN
--8. Tìm tên Sinh viên theo mã sinh viên
CREATE FUNCTION TimTenSinhVien(@MASINHVIEN varchar(15))
RETURNS TABLE
AS 
RETURN
SELECT NGUOIDUNG.HO , NGUOIDUNG.TEN
FROM SINHVIEN INNER JOIN NGUOIDUNG ON SINHVIEN.ID_NGUOIDUNG = NGUOIDUNG.ID_NGUOIDUNG
WHERE SINHVIEN.MASINHVIEN = @MASINHVIEN





--9. Lấy mã loại phòng bằng tên loại phòng
CREATE  FUNCTION UFN_LayMaLoaiPhongBangTenLoaiPhong(@TENLOAIPHONG NVARCHAR(20))
	RETURNS INT
AS
BEGIN
	DECLARE @MALOAIPHONG INT
	SELECT @MALOAIPHONG = MALOAIPHONG FROM dbo.LOAIPHONG
	WHERE TENLOAIPHONG = @TENLOAIPHONG
	RETURN @MALOAIPHONG
END
GO

SELECT dbo.UFN_LayMaLoaiPhongBangTenLoaiPhong(N'Phòng tám')
SELECT * FROM LOAIPHONG
--10. Lấy mã dịch vụ bằng tên dịch vụ và mã đơn vị
CREATE  FUNCTION UFN_LayMaDichVuBangTenDichVuVaMaDonVi(@TENDICHVU NVARCHAR(50) ,@MADONVI INT)
	RETURNS INT
AS
BEGIN
	DECLARE @MADICHVU INT
	SELECT @MADICHVU = MADICHVU FROM dbo.DICHVU
	WHERE TENDICHVU = @TENDICHVU AND MADONVI = @MADONVI
	RETURN @MADICHVU
END
GO

SELECT dbo.UFN_LayMaDichVuBangTenDichVuVaMaDonVi(N'Đổ rác ','3')
SELECT * FROM DICHVU

--11. Giao diện Bill
GO
CREATE OR ALTER FUNCTION UFN_ReturnForViewBillDetail
(
	@TENKHUVUC VARCHAR(10), 
	@MAPHONG NVARCHAR(10), 
	@THANG INT, 
	@NAM INT
)
RETURNS @View_BillDetail TABLE (
	MADICHVU INT, 
	TENDICHVU NVARCHAR(50), 
	TENDONVI NVARCHAR(50), 
	DONGIA DECIMAL(19,4), 
	SOCU INT, 
	SOMOI INT, 
	TONGIA DECIMAL(19,4),
	MACTHD INT, 
	HOADON INT)
AS
BEGIN
    DECLARE @MAHOADON INT, @MADICHVU NVARCHAR(50)
	SELECT @MAHOADON = dbo.UFN_LayMaHoaDon(@TENKHUVUC,@MAPHONG,@THANG,@NAM)

	INSERT INTO @View_BillDetail
	SELECT 
		BD.MADICHVU, 
		S.TENDICHVU, 
		BD.TENDONVI, 
		S.DONGIA, 
		BD.SOCU, 
		BD.SOMOI, 
		BD.TONGIA, 
		BD.MACTHD, 
		BD.MAHOADON
	FROM dbo.CTHD AS BD
		INNER JOIN dbo.DICHVU AS S ON S.MADICHVU = BD.MADICHVU 
		INNER JOIN dbo.HOADON AS B ON B.MAHOADON = BD.MAHOADON
	WHERE BD.MAHOADON = @MAHOADON
	RETURN
END
GO

--12. HÀM TÌM TÊN GẦN ĐÚNG